version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - run: whoami 
      - run: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'  
      - run: wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add - 
      - run: sudo apt-get update
      - run: sudo apt install postgresql-client-9.6
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE test (names char(25));"
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "INSERT INTO test (names) values ('testbed')"
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "SELECT * from test"
workflows:
  test_my_app:
    jobs:
      - build